# Generated by Django 5.1.6 on 2025-03-13 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0002_category_payment_customuser_phone_notification_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
