# Generated by Django 5.1.6 on 2025-03-13 01:34

import Account.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0003_room_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roomimage',
            name='image',
            field=models.ImageField(upload_to=Account.models.upload_path),
        ),
    ]
