# Generated by Django 5.1.6 on 2025-03-14 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0005_reservation_completed_reservation_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
