# Generated by Django 5.1.6 on 2025-03-14 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0006_alter_reservation_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
