# Generated by Django 5.1.6 on 2025-03-19 04:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0010_remove_review_comment_remove_review_created_at_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='review',
            unique_together={('user', 'room')},
        ),
    ]
