# Generated by Django 5.1.6 on 2025-03-27 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0011_alter_review_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='price_per_night',
            field=models.DecimalField(decimal_places=0, max_digits=10),
        ),
    ]
